Release

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -12,7 +12,6 @@ jobs:
   release:
     if: contains(github.event.head_commit.message, 'Release')
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -23,12 +22,6 @@ jobs:
         uses: actions/setup-go@v4
         with:
           go-version: "1.23"
-
-      - name: Debug logs
-        run: |
-          git fetch --tags
-          git tag
-          git describe --tags --abbrev=0 || echo "No tags found"
 
       - name: Get current tag
         id: get_version
@@ -41,7 +34,6 @@ jobs:
         run: |
           CURRENT_TAG="${{ env.current_tag }}"
           echo "Current Tag: $CURRENT_TAG"
-
           if [[ "$CURRENT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             BASE_VERSION=$(echo "$CURRENT_TAG" | cut -d 'v' -f 2)
             MAJOR=$(echo "$BASE_VERSION" | cut -d '.' -f 1)
@@ -51,12 +43,10 @@ jobs:
           else
             NEXT_TAG="v0.0.1"
           fi
-
           while git rev-parse "$NEXT_TAG" >/dev/null 2>&1; do
             PATCH=$(echo "$NEXT_TAG" | cut -d '.' -f 3)
             NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
           done
-
           echo "Final Next Tag: $NEXT_TAG"
           echo "tag=$NEXT_TAG" >> $GITHUB_ENV
 
@@ -64,7 +54,7 @@ jobs:
         id: build
         run: |
           mkdir -p build
-          platforms=("aix/ppc64" "android/386" "android/amd64" "android/arm" "android/arm64" "darwin/amd64" "darwin/arm64" "dragonfly/amd64" "freebsd/386" "freebsd/amd64" "freebsd/arm" "freebsd/arm64" "freebsd/riscv64" "illumos/amd64" "ios/amd64" "ios/arm64" "js/wasm" "linux/386" "linux/amd64" "linux/arm" "linux/arm64" "linux/loong64" "linux/mips" "linux/mips64" "linux/mips64le" "linux/mipsle" "linux/ppc64" "linux/ppc64le" "linux/riscv64" "linux/s390x" "netbsd/386" "netbsd/amd64" "netbsd/arm" "netbsd/arm64" "openbsd/386" "openbsd/amd64" "openbsd/arm" "openbsd/arm64" "openbsd/ppc64" "openbsd/riscv64" "plan9/386" "plan9/amd64" "plan9/arm" "solaris/amd64" "wasip1/wasm" "windows/386" "windows/amd64" "windows/arm" "windows/arm64")
+          platforms=("linux/amd64" "linux/arm64" "windows/amd64" "darwin/amd64" "darwin/arm64")
           for platform in "${platforms[@]}"; do
             GOOS=${platform%/*}
             GOARCH=${platform#*/}
@@ -72,15 +62,8 @@ jobs:
             if [[ "$GOOS" == "windows" ]]; then
               EXTS=".exe"
             fi
-            if [[ "$GOARCH" == "amd64" ]]; then
-              for GOAMD64 in v2 v3; do
-                output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}${GOAMD64}${EXTS}
-                env GOOS=$GOOS GOARCH=$GOARCH GOAMD64=$GOAMD64 go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC' -o=$output_name" -gcflags="all=-l -B -trimpath=" -v || echo "Failed to build for $platform with $GOAMD64"
-              done
-            else
-              output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}${EXTS}
-              env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC' -o=$output_name" -gcflags="all=-l -B -trimpath=" -v || echo "Failed to build for $platform"
-            fi
+            output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}${EXTS}
+            env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC' -o=$output_name" -gcflags="all=-l -B -trimpath=" -v || echo "Failed to build for $platform"
           done
 
       - name: Create or Update Release
