测试

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -65,13 +65,21 @@ jobs:
           mkdir -p build
           platforms=("aix/ppc64" "android/386" "android/amd64" "android/arm" "android/arm64" "darwin/amd64" "darwin/arm64" "dragonfly/amd64" "freebsd/386" "freebsd/amd64" "freebsd/arm" "freebsd/arm64" "freebsd/riscv64" "illumos/amd64" "ios/amd64" "ios/arm64" "js/wasm" "linux/386" "linux/amd64" "linux/arm" "linux/arm64" "linux/loong64" "linux/mips" "linux/mips64" "linux/mips64le" "linux/mipsle" "linux/ppc64" "linux/ppc64le" "linux/riscv64" "linux/s390x" "netbsd/386" "netbsd/amd64" "netbsd/arm" "netbsd/arm64" "openbsd/386" "openbsd/amd64" "openbsd/arm" "openbsd/arm64" "openbsd/ppc64" "openbsd/riscv64" "plan9/386" "plan9/amd64" "plan9/arm" "solaris/amd64" "wasip1/wasm" "windows/386" "windows/amd64" "windows/arm" "windows/arm64")
           for platform in "${platforms[@]}"; do
-            GOOS=${platform%/*} 
+            GOOS=${platform%/*}
             GOARCH=${platform#*/}
-            output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}
+            EXTS=""
             if [[ "$GOOS" == "windows" ]]; then
-              output_name+='.exe'
+              EXTS=".exe"
             fi
-            env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC'" -gcflags="all=-l -B -trimpath=" -o $output_name -v || echo "Failed to build for $platform"
+            if [[ "$GOARCH" == "amd64" ]]; then
+              for GOAMD64 in v2 v3; do
+                output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}${GOAMD64}${EXTS}
+                env GOOS=$GOOS GOARCH=$GOARCH GOAMD64=$GOAMD64 go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC' -o=$output_name" -gcflags="all=-l -B -trimpath=" -v || echo "Failed to build for $platform with $GOAMD64"
+              done
+            else
+              output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}${EXTS}
+              env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC' -o=$output_name" -gcflags="all=-l -B -trimpath=" -v || echo "Failed to build for $platform"
+            fi
           done
 
       - name: Create or Update Release
@@ -82,9 +90,7 @@ jobs:
           tag_name: ${{ env.tag }}
           name: Release ${{ env.tag }}
           body: |
-            Changes in this Release
-            - First Change
-            - Second Change
+            **Full Changelog**: https://github.com/Sn0wo2/bilibilicomments/compare/${{ env.current_tag }}...${{ env.tag }}
           draft: false
           prerelease: false
           fail_on_unmatched_files: true
