测试

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -63,7 +63,7 @@ jobs:
         id: build
         run: |
           mkdir -p build
-          platforms=("darwin/amd64" "darwin/arm64" "linux/386" "linux/amd64" "linux/arm64" "linux/arm" "linux/ppc64le" "linux/mips" "linux/mipsle" "linux/mips64" "linux/mips64le" "windows/386" "windows/amd64" "windows/arm64")
+          platforms=("aix/ppc64" "android/386" "android/amd64" "android/arm" "android/arm64" "darwin/amd64" "darwin/arm64" "dragonfly/amd64" "freebsd/386" "freebsd/amd64" "freebsd/arm" "freebsd/arm64" "freebsd/riscv64" "illumos/amd64" "ios/amd64" "ios/arm64" "js/wasm" "linux/386" "linux/amd64" "linux/arm" "linux/arm64" "linux/loong64" "linux/mips" "linux/mips64" "linux/mips64le" "linux/mipsle" "linux/ppc64" "linux/ppc64le" "linux/riscv64" "linux/s390x" "netbsd/386" "netbsd/amd64" "netbsd/arm" "netbsd/arm64" "openbsd/386" "openbsd/amd64" "openbsd/arm" "openbsd/arm64" "openbsd/ppc64" "openbsd/riscv64" "plan9/386" "plan9/amd64" "plan9/arm" "solaris/amd64" "wasip1/wasm" "windows/386" "windows/amd64" "windows/arm" "windows/arm64")
           for platform in "${platforms[@]}"; do
             GOOS=${platform%/*} 
             GOARCH=${platform#*/}
@@ -71,7 +71,7 @@ jobs:
             if [[ "$GOOS" == "windows" ]]; then
               output_name+='.exe'
             fi
-            env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC'" -gcflags="all=-l -B -trimpath=" -o $output_name -v
+            env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC'" -gcflags="all=-l -B -trimpath=" -o $output_name -v || echo "Failed to build for $platform"
           done
 
       - name: Create or Update Release
